### ISSUE TITLE
Suggestion: More than one source

### ISSUE THREAD

**Issue by lolhart** [kz26/dottorrent-gui#8]
Hello, is it possible to have the feature to add more than one source when creating a torrent? This would be very helpful when sharing across more than one private tracker. Thanks.

**Comment by kz26** [comment]
What do you mean by "more than one source"? Changing the source would require the creation of a new torrent file.

**Comment by tn5421** [comment]
What I believe he means is that he wants to do the creation process one time only, using more than one profile.  Say he wants to upload to rutracker and apollo.  What he wants is to go through making the torrent only once, but have it spit out two torrent files, one for rutracker and one for apollo, each configured correctly beforehand via .json profile settings.

**Comment by kz26** [comment]
I'm not sure whether this sort of feature would be appropriate for the GUI due to the complexity involved of displaying/loading multiple profiles and adding another automation layer to the creation process. I think this sort of task would be more suited to automating the dottorrent CLI using a shell script.
